### ISSUE TITLE
Iconify Off changes Layer

### ISSUE THREAD

**Issue by petergthatsme** [fvwmorg/fvwm#15]
Finally got around to trying the master branch from github (have been running the cvs version from before the switch, up until a few days ago). 

I noticed that after calling "Iconify Off" on a window, I see the layer listed as "2", even though before calling "Iconify On" on this window, it was (say) "4". It this a bug? 
thanks

**Comment by ThomasAdam** [comment]
Nope, not a bug since I can't reproduce it.  Do you get the same result if you try it with:  `fvwm -f /dev/null`?  If you don't then there's something in your config causing it.  You can always create a Gist of it for me to take a look...

**Comment by petergthatsme** [comment]
Indeed, I was also calling the window's style as StaysOnBottom, as I was iconizing, which (now?) sets the Layer to "2". Double checked again the older cvs version (from ~Dec 2015) I was running earlier, and that version does not change the Layer to "2" during that call. The docs seem to say that StaysOnBottom should - so maybe that just got fixed?

either way, this can be closed - thanks.
