### ISSUE TITLE
conan.io

### ISSUE THREAD

**Issue by jouana** [fvwmorg/fvwm#16]
Hi,
To manage dependencies its possible to use [conan.io](https://www.conan.io/)?
It's just an idea.

Have a good day.

**Comment by ThomasAdam** [comment]
Hi,

What benefit does this bring?  It seems like an over-engineered solution to a problem that doesn't exist.

**Comment by jouana** [comment]
Hi,
It's just an Idea to manage external dependencies, for simplify build on install

**Comment by ThomasAdam** [comment]
Well, I can't see how that help at all, having to rely on a third-party like this, when automake is already enforcing that to some extent.  Until you can show me what it does, and how you think it will benefit this project, I'm not sure what else I can say.

**Comment by dumblob** [comment]
Speaking about build tooling, if there was an utter need to change anything, I would go for [Ekam](https://github.com/sandstorm-io/ekam ) (full automation, simplicity) or [Premake](http://premake.github.io/ ).
