### ISSUE TITLE
Action "-" no longer works for passthrough

### ISSUE THREAD

**Issue by stanford-scs** [fvwmorg/fvwm#18]
Older versions of fvwm used to allow a specific binding to be removed with the "-" or "--" function.  This was particularly useful for applications that need window manager bindings, like vncviewer where one might run a window manager inside a VNC window.  Previously, I would configure fvwm like this:

Key F4		FSTW	4	Close
Key (Vncviewer) F4		W	M	--

In the past, this made Alt-F4 close any window except Vncviewer, and on top of Vncviewer it would pass the Alt-F4 event through to the underlying window manager in my VNC session.

More recently, however (I'm now on fvwm 2.6.6), this stopped working.  I don't know if the previous behavior was intended, but it was extremely useful, so consider this either a bug report or a feature request to bring back the old behavior, or provide some alternate means of passing events to specific underlying applications, even when those events have some alternate meaning in any other context..

Thanks.

**Comment by ThomasAdam** [comment]
Window-specific bindings rely on the application receiving synthetic events.  This used to be quite common, but in more recent times has been a security concern, so not many applications accept them (XTerm does, but you have to tell it to allow them, for instance).

Hence, this feature in FVWM has been removed.

There's nothing FVWM can do about this.
