### ISSUE TITLE
New Configuration File Needed

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm#19]
See:  https://github.com/fvwmorg/fvwm/blob/ta/new-config-format/docs/NEW-CONFIG.md

Comments welcome.

**Comment by xmstspider** [comment]
Hi Thomas,

I read through the NEW-CONFIG.md document, and even I found your idea interesting, I have one question - didn't you consider using some existing configuration format like INI or JSON instead of building a completely new one, or possibly using some TDL for generating the final configuration?

**Comment by ThomasAdam** [comment]
@xmstspider -- yes, I did consider INI and JSON and they're inflexible for what I'm trying to achieve.  JSON in particular is not suited to configuration files at all (this is a good read:  http://arp242.net/weblog/JSON_as_configuration_files-_please_dont.html).  More fundamentally though, I want the configuration format and the way of interacting with FVWM to be consistent, and to have defined areas of a scripting syntax which allows for this isn't easily represented in these formats either.

**Comment by xmstspider** [comment]
Understand. What about some TDL like it is used in Ansible/Cfengine/Puppet?

The reason why I am asking is that I really like the FVWM and I welcome your idea, some time back I started working on a way to to script the configuration using a TDL. The goal was not like Sendmail with M4, but more an interface which is understandable more that the FVWM config.

**Comment by ThomasAdam** [comment]
Not really a TDL, no.

**Comment by xmstspider** [comment]
OK, no problem. Thanks.

**Comment by gdiazlo** [comment]
https://github.com/hashicorp/hcl, I like the format, not implemented in C though

**Comment by ThomasAdam** [comment]
That's no different to libucl.

**Comment by dumblob** [comment]
I've looked at the proposal and I'm sure about 2 things.

1. We need turing complete language for configuration (even my FVWM config is about 2500 lines of code full of "dynamic" sections calling shell or other utilities to add two numbers or do some simple string operations or find some files or construct complex menus, etc.).

1. To address the need to be able to write line-based configs (at least to greatly simplify conversion scripts) and based on my experience with languages, their embedding, issues with DSLs etc., I'm sure **Lua is the way to go**. Except for being really minimal, developed, widespread, comprehensive, extremely fast (fastest interpreted language in the world), readable, etc., it's syntax rules allow "mimicking" the [line-based nature](https://github.com/premake/premake-core/wiki/Your-First-Script ) (read the whole chapter to understand how far we can go).

Of course, for configuration files, there are more good (and even tinier and more cute) options I wanted to propose, but that would require a significant shift in thinking - namely the acceptance, that there are maybe 100 users of FVWM all around the world and those are power users who won't have any issue with rewriting of their configs to a completely unrelated language. Anyway, I'm talking about [Dao](https://github.com/daokoder/dao ), Lisp-like languages (e.g. [JL](https://github.com/joewing/jl )) or Smalltalk-like languages (e.g. [Wren](https://github.com/munificent/wren)) where all these are really tiny, embeddable, very fast (almost like Lua and way faster than Python/Ruby/etc.) and well-proven by time.

**Comment by dumblob** [comment]
Forgot to react to the subtle, but actually most important clarification of the "new configuration file" goals described in https://www.mail-archive.com/fvwm-workers@fvwm.org/msg03576.html . Namely, that it's neither about syntax, nor about language, but about a language-agnostic API.

I'm confident we should let us inspire by Neovim as it's pretty much the same situation as FVWM. Neovim has it's own cryptic "configuration language", but needs to have a totally language-agnostic API, which is thread- and process- safe, very fast and lean. I would therefore highly recommend to study in detail how the [Neovim API](https://github.com/neovim/neovim/tree/master/src/nvim/api ) looks like (it's using MessagePack btw).

The auto-generated always up to date Neovim API for Node.js can be found in https://github.com/neovim/node-client/blob/master/index.d.ts . There are plenty of [API-related issues](https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=label%3Aapi%20 ) useful to study why certain decisions were made.
