### ISSUE TITLE
fvwm-convert-2.4 and fvwm-convert-2.6 are without execute bits

### ISSUE THREAD

**Issue by volkers** [fvwmorg/fvwm#22]
Minor issue but only fvwm-convert-2.2 got the execute bits:

~/ftp/fvwm/fvwm_git/bin
> ls -l *convert*
-rwxr-xr-x 1 vos vos 16922 Oct 18 11:38 fvwm-convert-2.2*
-rw-r--r-- 1 vos vos  1124 Oct 18 11:43 fvwm-convert-2.2.1
-rw-r--r-- 1 vos vos  1095 Oct 18 11:38 fvwm-convert-2.2.1.in
-rw-r--r-- 1 vos vos  9664 Oct 18 11:43 fvwm-convert-2.4
-rw-r--r-- 1 vos vos  4183 Oct 18 11:43 fvwm-convert-2.4.1
-rw-r--r-- 1 vos vos  4154 Oct 18 11:38 fvwm-convert-2.4.1.in
-rw-r--r-- 1 vos vos  9624 Oct 18 11:38 fvwm-convert-2.4.in
-rw-r--r-- 1 vos vos 14482 Oct 18 11:43 fvwm-convert-2.6
-rw-r--r-- 1 vos vos  3684 Oct 18 11:43 fvwm-convert-2.6.1
-rw-r--r-- 1 vos vos  3655 Oct 18 11:38 fvwm-convert-2.6.1.in
-rw-r--r-- 1 vos vos 14475 Oct 18 11:38 fvwm-convert-2.6.in

Regards
Volker

**Comment by ThomasAdam** [comment]
This is because `bin_SCRIPTS` only applies when the `install-exec` is run.

I have, however, removed all the older conversion scripts which are no longer necessary.
