### ISSUE TITLE
TODO: The module interface (FVWM <-> Module)

### ISSUE THREAD

**Issue by dumblob** [fvwmorg/fvwm#23]
In https://github.com/fvwmorg/fvwm/commit/7ccbb2154ad103f728a89b1371f5c8b24720910f there are 2 things mixed - buses and packing/transfer protocols. Depending on the use case (do we want modules to run separately as processes or rather "inside" of FVWM) either of them will be chosen. I'd like to add two more items to the list:

1. [Cap'n Proto](https://capnproto.org/ ) - minimal, fastest in the world, "successor" of Protocol Buffers, from the creator of Protocol Buffers
1. [ubus](https://wiki.openwrt.org/doc/techref/ubus ) - minimal, fast, no bloat, low resource demands (memory, CPU, disk space)

**Comment by ThomasAdam** [comment]
Thanks; they're mixed in deliberately since you wouldn't separate out the two when doing the work anyway.

I'll consider these as well.
