### ISSUE TITLE
Wayland and/or backend-agnostic with Nuklear

### ISSUE THREAD

**Issue by dumblob** [fvwmorg/fvwm#24]
With the very fast advent (and spreading into *nix distributions) of Wayland, I'd like to ask if there are any plans to "migrate" FVWM to Wayland?

With this in mind, a better question might be whether to migrate directly to a backend-agnostic solution for rendering (e.g. [Nuklear](https://github.com/vurtun/nuklear )) and drop the X11, Freetype2, Perl, etc. dependencies completely or make them optional. Why directly to Nuklear? Because Wayland does not offer any window abstractions (think of FVWM pager), no widgets/drawing_primitives (think of FVWM menus, borders, titles, etc.), no X11-like "atoms", no rendering (just compositing operations), no client-side ("in-window") drawing, etc. This everything is offered by Nuklear.

**Comment by ThomasAdam** [comment]
This will be a candidate for fvwm-3 most likely, but it's not a priority.

**Comment by dumblob** [comment]
I would leave it open then and add a flag "fvwm-3.0.0".

**Comment by ThomasAdam** [comment]
That's not necessary. It's added to the TODO file.
