### ISSUE TITLE
Lost png support?

### ISSUE THREAD

**Issue by volkers** [fvwmorg/fvwm#25]
I updated (from cvs) to the latest version in git, but
unfortunately lost png support under the transition.

configure showed:

checking for libpng...... checking pkg-config is at least version 0.9.0... yes
checking for png... yes

but when running only xpms are shown.

fvwm -V
fvwm version-2_6_6-105-gccc093f compiled on Oct 21 2016 at 09:52:24
with support for: ReadLine, RPlay, Stroke, XPM, SVG, Shape, XShm, SM, Xinerama, XRender, XCursor, XFT, NLS

Is there an additional step I am missing?

Kind regards
Volker

I got the following errors when running config:

./configure: line 13199: GNOME_INIT_HOOK: command not found
config.status: error: cannot find input file: `bin/fvwm-convert-2.2.1.in'

and this is the complete output of configure:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for sed... sed
checking for a Python interpreter with version >= 2.5... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for perl... /usr/bin/perl
checking for perl 5.004 or better... yes
assuming /usr/bin/perl as perl location
checking whether to enable command logging... no
checking whether to enable debugging messages... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for X... libraries , headers
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking imagepath... /usr/include/X11/bitmaps:/usr/include/X11/pixmaps
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking for library containing strerror... none required
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking size of int... 4
checking size of long... 8
checking size of Window... 8
checking size of Pixel... 8
checking size of void *... 8
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pkg-config... /usr/bin/pkg-config
checking for xsltproc... xsltproc
checking for SmcOpenConnection in -lSM... yes
checking for XShapeQueryExtension in -lXext... yes
checking for XShmQueryExtension in -lXext... yes
checking X11/XKBlib.h usability... yes
checking X11/XKBlib.h presence... yes
checking for X11/XKBlib.h... yes
checking for XineramaIsActive in -lXinerama... yes
checking whether to enable Xinerama emulation on one screen (useful only for developers)... no
checking for XRenderComposite in -lXrender... yes
checking for XRenderCreateCursor in -lXrender... yes
checking for XcursorImageLoadCursor in -lXcursor... yes
checking for freetype-config... /usr/bin/freetype-config
checking for FreeType - version >= 6.1.0... yes
checking for fontconfig-config... no
checking for Fontconfig - version >= 1.0.1... yes
checking for xft-config... no
checking for Xft - version >= 2.0.0... yes
checking for XpmReadFileToXpmImage in -lXpm... yes
checking X11/xpm.h usability... yes
checking X11/xpm.h presence... yes
checking for X11/xpm.h... yes
checking for Xpm 3.4g or better... yes
checking for libpng...... checking pkg-config is at least version 0.9.0... yes
checking for png... yes
checking whether byte ordering is bigendian... no
checking for librsvg - version >= 2.13.92... yes
checking for cairo svg backend... yes
checking whether a librsvg program compiles and runs... yes
checking for rplay_create in -lrplay... yes
checking rplay.h usability... yes
checking rplay.h presence... yes
checking for rplay.h... yes
checking for stroke_init in -lstroke... yes
checking stroke.h usability... yes
checking stroke.h presence... yes
checking for stroke.h... yes
checking with termcap... checking for readline in -lreadline... yes
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking for append_history in -lreadline... yes
checking for _Xsetlocale in -lX11... no
checking for XOpenOM in -lX11... yes
checking for libiconv_open in -liconv... no
checking for iconv_open... yes
checking check if second arg of iconv is const... no
checking for nl_langinfo (CODESET)... yes
checking for fribidi-config... no
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msguniq... /usr/bin/msguniq
checking for NLS fvwm messages catalogs... ar de fr sv_SE zh_CN ru es
checking for NLS desired catalogs to be installed... all
checking for NLS messages catalogs to be installed...  ar de fr sv_SE zh_CN ru es
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for gettext... yes
checking for bindtextdomain... yes
checking for textdomain... yes
checking for dgettext... yes
checking for gnu gettext in libc... yes
checking if a simple gettext program link... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for vfprintf... yes
checking for waitpid... yes
checking for sigsetjmp... no
checking for siglongjmp... yes
checking for cpp... /usr/bin/cpp
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for stdlib.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for unistd.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/systeminfo.h usability... no
checking sys/systeminfo.h presence... no
checking for sys/systeminfo.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking return type of signal handlers... void
checking for strftime... yes
checking whether setpgrp takes no argument... yes
checking for gettimeofday... yes
checking for mkfifo... yes
checking for putenv... yes
checking for setvbuf... yes
checking for socket... yes
checking for waitpid... (cached) yes
checking for strdup... yes
checking for strstr... yes
checking for strtol... yes
checking for memmove... yes
checking for memcpy... yes
checking for strchr... yes
checking for sysconf... yes
checking for uname... yes
checking for div... yes
checking for sigaction... yes
checking for siginterrupt... yes
checking for getpwuid... yes
checking for setpgrp... yes
checking for setpgid... yes
checking for lstat... yes
checking for sig_atomic_t... yes
checking for select... yes
checking for unistd.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for sys/select.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking argument types of select()... select(int,fd_set *,...)
checking for mkstemp... yes
checking if mkstemp is safe... yes
checking for imlib-config... no
checking for GDK IMLIB - version >= 1.8.0... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libs/Makefile
config.status: creating fvwm/Makefile
config.status: creating modules/Makefile
config.status: creating bin/fvwm-bug.1
config.status: creating bin/fvwm-config.1

**Comment by ThomasAdam** [comment]
At the moment, that's correct.  `libpng` is mandatory, although I'll be tweaking that slightly to make it optional.

Your additional error is because you didn't run `autogen.sh` first when then running `./configure`

**Comment by volkers** [comment]
Quick response, thanks!
But the question was not whether libpng is or is not mandatory. The problem is that png icons are no longer shown (but xpm's are), i.e. png rendering doesn't work.

**Comment by ThomasAdam** [comment]
What does `ldd $(which fvwm)` (or the path to the fvwm binary you built) show?

**Comment by volkers** [comment]
linux-vdso.so.1 (0x00007ffc39be5000)
	libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2 (0x00007fa467155000)
	libXpm.so.4 => /usr/lib/x86_64-linux-gnu/libXpm.so.4 (0x00007fa466f43000)
	libstroke.so.0 => /usr/lib/libstroke.so.0 (0x00007fa466d41000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fa466b39000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fa46691c000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fa466719000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa466507000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa4661c4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa465ec3000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fa465cb9000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fa465aae000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fa465887000)
	librsvg-2.so.2 => /usr/lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007fa465650000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fa4652d6000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fa4650b4000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fa464e61000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fa464b52000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fa464838000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fa4645fb000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa464351000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa463fa6000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa463da1000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa463b7f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa46397b000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fa463775000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa46355a000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fa46334d000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fa4630ff000)
	libcroco-0.6.so.3 => /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3 (0x00007fa462ec4000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fa462b5d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa462940000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fa46273c000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fa462517000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa462300000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fa4620f8000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa461e8a000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fa461bdd000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fa4619d9000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fa4617cf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa4615c7000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa46139e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa46736b000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa46119a000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa460f95000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fa460d93000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fa460b7d000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fa460974000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa460751000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fa4604fa000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fa4602f2000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fa4600cc000)

**Comment by ThomasAdam** [comment]
Please try this branch:  `https://github.com/fvwmorg/fvwm/tree/ta/png-support-fix` (ta/png-support-fix) -- does this help?

**Comment by volkers** [comment]
It works, png's are back!

Thanks
Volker

**Comment by ThomasAdam** [comment]
Cool -- I'll leave you with that for now, and over the weekend I'll put something proper in place.
