### ISSUE TITLE
Enhancement: Scale height and width of menu item image (icon)

### ISSUE THREAD

**Issue by dumblob** [fvwmorg/fvwm#28]
FVWM supports pixmaps (PNG, JPG, ...) as well as vector images (SVG) and in modern application distributions these are available in high resolutions. This causes huge troubles for auto-generated menus (e.g. XDG one) as the height of each menu item is determined as `max(text_height + text_padding, image_height)` and therefore menu items have wildly varying heights which is more than inconvenient.

I'd like to propose automatical scaling of menu item image height to the height `font_height + font_padding` and scaling the menu item image width with the same ratio. This will ensure preservation of correct ratios of non-square images while maintaining the same height for all menu items.

**Comment by ThomasAdam** [comment]
This would be quite invasive with a lot of the other menu options we have.

**Comment by dumblob** [comment]
Let's add a new option for that then.

**Comment by somiaj** [comment]
the fvwm-menu-desktop script already does this. If ImageMagick is installed it will resize all icons to a specified size. I won't calculate the height you need, but you can have it generate menus in which all the icons are resized to 20x20.

**Comment by dumblob** [comment]
@somiaj thanks for bringing it up.

I knew about this capability of the `fvwm-menu-desktop` script. But that's not exactly what I envision. It is highly redundant and inefficient to call external image processing applications (e.g. [GraphicsMagick](http://www.graphicsmagick.org/ )) to scale images, then temporarily save them somewhere, keep the image cache up to date (image name and date is not enough, so we need binary 3-way diff), and first then use them in FVWM.

It's easier, way more convenient, and an order of magnitude faster (because all image backends FVWM uses for PNGs, SVGs, etc. support scaling) to just use FVWM pipe read with something like `"$(for t in "$HOME/my/own/menu/images" /usr/share/icons/highest_priority_theme /usr/share/icons/*; do find "$t" -type d | sort -n; done)"` to effortlessly achieve "at least some image in the menu if not available in the chosen theme" behavior (which is I assume the whole point of having images in menu).

Needless to say, such "automatical eye candy" would bring new users (potential contributors) to the good old FVWM, because nowadays basically all other wider-spread WMs (and desktop environments as well, of course) scale images in menus by default. On the other hand, I have no idea what are the long-term plans for FVWM (in `TODO.md` there are some tiny bits scattered, but not comprehensive), so feel free to correct me.

**Comment by somiaj** [comment]
I think some of your info is incorrect, but I'm no expert. Fvwm only supports 3 image formats xpm, png (via libpng) and svg. Of those three, only svg supports scaling in the library and fvwm uses this. If using svg icons were being used these can be easily scaled with fvwm already. So fvwm already support scaling on the image library backend which supports this (.svg).

libpng is an i/o library and doesn't seem to support scaling (found multiple stackexchange/overfloow sources to back this up). So I think in this case using a third party scaling app like imagemagick is just fine for someone who wants to scale png icons as this is a feature not supported by the backend like you claim.

But this is off point. I was just trying to provide a solution which works just fine here to get icons in XDG menus of a certain size. I don't see any reason why fvwm needs to include more image libraries (or its own internal image functions) just to resize menu icons when imagemagick does the job just fine.

**Comment by danespen** [comment]
dumblob <notifications@github.com> writes:

> @somiaj thanks for bringing it up.
>
> I knew about this capability of the fvwm-menu-desktop script. But
> that's not exactly what I envision. It is highly redundant and
> inefficient to call external image processing applications (e.g.
> GraphicsMagick) to scale images, then temporarily save them somewhere,
> keep the image cache up to date (image name and date is not enough, so
> we need binary 3-way diff), and first then use them in FVWM.

That is not how Fvwm manages the icon cache.
The match to cache is size and image name.
Like:

24x24-xsane.xpm

Works very efficiently and I see no reason to change the existing
functionality.

-- 
Dan Espen
