### ISSUE TITLE
Fedora 26 fvwm-menu-desktop not working

### ISSUE THREAD

**Issue by pyaazkaparatha** [fvwmorg/fvwm#42]
```
bash-4.4$ fvwm --version
fvwm 2.6.7 compiled on Feb 10 2017 at 16:19:26
with support for: ReadLine, Stroke, XPM, SVG, Shape, XShm, SM, Bidi text, Xinerama, XRender, XCursor, XFT, NLS
```

The error
```
bash-4.4$ fvwm-menu-desktop --desktop gnome
  File "/usr/bin/fvwm-menu-desktop", line 144
    except getopt.GetoptError, err:
                             ^
SyntaxError: invalid syntax



```

**Comment by somiaj** [comment]
Hello,

There is an issue with the build scripts detecting and using python3 on some systems as the shebang, and this is an older python script that may not be compatible with python3. A proper fix would be fixing the autoconf scripts to force dependency on python2 so python3 is not used for this script.

Check the shebang in the built script on the system, and change it to python2, this should fix the issues. In Debian I have forced the build to make the shebang points to python2 to avoid this issue.

This may not be the only issue with the script with using python3. Before accepting this fix, make sure the script works in python3 to ensure this is the only issue that prevents this script from running with python3.

For now I suggest you force the script to use python2.

**Comment by somiaj** [comment]
One additional note, this fix will work just fine in python 2 and we could accept it, I just don't think this is enough to make the script python 3 compatible and suggest you use python 2 for this script if possible.

**Comment by pyaazkaparatha** [comment]
Thanks. Changing to python2 and installing the python2-pyxdg package helped.

**Comment by pyaazkaparatha** [comment]
It still gives error. 

`bash-4.4$ fvwm-menu-desktop
  File "/usr/bin/fvwm-menu-desktop", line 146
    print str(err) # will print something like "option -a not recognized"
            ^
SyntaxError: invalid syntax
`

This is with python3

`fvwm 2.6.7 compiled on Apr 11 2017 at 14:20:21`

**Comment by somiaj** [comment]
As said previously, the python script fvwm-menu-desktop was written for python2, so please use python2, not python3.

There are enough differences between python2 and python3 and this script has not been updated to the differences so some parts may fail if using python3. Use python2 to run fvwm-menu-desktop.

**Comment by danespen** [comment]
Jaimos <notifications@github.com> writes:

> As said previously, the python script fvwm-menu-desktop was written
> for python2, so please use python2, not python3.
>
> There are enough differences between python2 and python3 and this
> script has not been updated to the differences so some parts may fail
> if using python3. Use python2 to run fvwm-menu-desktop.

Based on some quick testing,
the only python2 vs. python3 change that affects this script
is that all "print" arguments must be surrounded by parens
which were previously optional.

-- 
Dan Espen

**Comment by somiaj** [comment]
On Mon, Jun 5, 2017 at 7:52 PM, danespen <notifications@github.com> wrote:

> Jaimos <notifications@github.com> writes:
>
> > As said previously, the python script fvwm-menu-desktop was written
> > for python2, so please use python2, not python3.
> >
> > There are enough differences between python2 and python3 and this
> > script has not been updated to the differences so some parts may fail
> > if using python3. Use python2 to run fvwm-menu-desktop.
>
> Based on some quick testing,
> the only python2 vs. python3 change that affects this script
> is that all "print" arguments must be surrounded by parens
> which were previously optional.
>
>
Thanks for testing Dan. I was unsure what differences there was and didn't
want to go down that rabbit hole. If it is really just an issue with
quoting some print statements and it runs in both  python2 and python3, it
may be worth updating it. I was just afraid it was going to be lots of
updates.

jaimos

**Comment by pyaazkaparatha** [comment]
What should be done to use it with python2? I changed the top line to python2 instead of python3. Now i get this error.

`bash-4.4$ fvwm-menu-desktop 
Traceback (most recent call last):
  File "/usr/bin/fvwm-menu-desktop", line 783, in <module>
    main()
  File "/usr/bin/fvwm-menu-desktop", line 179, in main
    if os.path.isfile("%s/.FvwmForm-XDGMenu-Config" % os.environ['FVWM_USERDIR']):
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'FVWM_USERDIR'
`

I am using fvwm on Fedora 26

**Comment by somiaj** [comment]
On Mon, Jun 5, 2017 at 9:51 PM, pyaazkaparatha <notifications@github.com>
wrote:

> What should be done to use it with python2? I changed the top line to
> python2 instead of python3. Now i get this error.
>
> bash-4.4$ fvwm-menu-desktop Traceback (most recent call last): File
> "/usr/bin/fvwm-menu-desktop", line 783, in <module> main() File
> "/usr/bin/fvwm-menu-desktop", line 179, in main if
> os.path.isfile("%s/.FvwmForm-XDGMenu-Config" %
> os.environ['FVWM_USERDIR']): File "/usr/lib64/python2.7/UserDict.py",
> line 40, in __getitem__ raise KeyError(key) KeyError: 'FVWM_USERDIR'
>
> I am using fvwm on Fedora 26
>
>
> Are you running fvwm when you run that script? There was a bug in the 2.7
version that would error out if you didn't have FVWM_USERDIR defined. If
you are running this from FVWM this should not be an issue. This bug has
been fixed in a more recent version which can be found in git. Here is the
commit

https://github.com/fvwmorg/fvwm/commit/a6fbeb7997a4310217c6b9f41fca4a8b1ab3b99d

You could also just do FVWM_USERDIR=$HOME/.fvwm fvwm-menu-desktop to get it
to work if not running fvwm.

jaimos

**Comment by danespen** [comment]
Jaimos <notifications@github.com> writes:

> On Mon, Jun 5, 2017 at 7:52 PM, danespen <notifications@github.com> wrote:
>
>> Jaimos <notifications@github.com> writes:
>>
>> > As said previously, the python script fvwm-menu-desktop was written
>> > for python2, so please use python2, not python3.
>> >
>> > There are enough differences between python2 and python3 and this
>> > script has not been updated to the differences so some parts may fail
>> > if using python3. Use python2 to run fvwm-menu-desktop.
>>
>> Based on some quick testing,
>> the only python2 vs. python3 change that affects this script
>> is that all "print" arguments must be surrounded by parens
>> which were previously optional.
>>
>>
> Thanks for testing Dan. I was unsure what differences there was and didn't
> want to go down that rabbit hole. If it is really just an issue with
> quoting some print statements and it runs in both python2 and python3, it
> may be worth updating it. I was just afraid it was going to be lots of
> updates.

Sorry, a little more testing shows some other changes are needed but
nothing major.  Replace "has_key", no comma in except, don't mix
tabs/spaces.

Still, not any significant changes.

-- 
Dan Espen
