### ISSUE TITLE
Invalid _NET_WM_ICON content allows applications to crash fvwm

### ISSUE THREAD

**Issue by lvml** [fvwmorg/fvwm#45]
I noticed that my fvwm crashed / dumped core when running http://assets.unigine.com/d/Unigine_Valley-1.0.run (the starter menu works, the crash happenes once the actual demo window is opened when you click the "Run"-button).

The crash occured 100% reproducible with this stack trace:
```
#0  0x0000000000477158 in extract_wm_icon (best_h=<synthetic pointer>, best_w=<synthetic pointer>, start_best=<synthetic pointer>, wanted_h=16, wanted_w=16, size=1026, list=0x1d11550) at ewmh_icons.c:668
#1  0x0000000000477158 in EWMH_SetIconFromWMIcon (fw=fw@entry=0x1d08300, list=list@entry=0x1d11550, size=<optimized out>, is_mini_icon=is_mini_icon@entry=1) at ewmh_icons.c:740
#2  0x00000000004776e7 in ewmh_WMIcon (fw=fw@entry=0x1d08300, ev=ev@entry=0x0, style=style@entry=0x0, any=any@entry=0)
    at ewmh_icons.c:105
#3  0x000000000045abfe in EWMH_WindowInit (fw=fw@entry=0x1d08300) at ewmh.c:1703
#4  0x0000000000441eca in AddWindow (ret_initial_map_command=ret_initial_map_command@entry=0x7ffc48b0dc28, exc=0x1cb2b10, ReuseWin=ReuseWin@entry=0x0, win_opts=win_opts@entry=0x7ffc48b0dc50) at add_window.c:2657
#5  0x000000000042abf3 in HandleMapRequestKeepRaised (ea=0x7ffc48b0dde0, KeepRaised=0, ReuseWin=0x0, win_opts=0x7ffc48b0dc50)
    at events.c:3126
#6  0x000000000042bb17 in dispatch_event (e=e@entry=0x7ffc48b0de60) at events.c:4306
#7  0x000000000042c88d in HandleEvents () at events.c:4357
#8  0x000000000040ae3a in main (argc=<optimized out>, argv=<optimized out>) at fvwm.c:2599
```

I debugged this and found that the culprit is blind trust in the validity of the data an application returns for _NET_WM_ICON: In the case of above linked "valley"-demo, the width of the first icon in the "list" is ok, but the height is some arbitrary large number. This causes an overflow when multiplying list[i]*list[i+1], resulting in a negative index and thus a SEGFAULT.

I helped myself with this patch, which allows the the "valley" demo to run fine:
```
--- fvwm/ewmh_icons.c.orig      2017-04-08 22:08:33.581536752 +0200
+++ fvwm/ewmh_icons.c   2017-04-08 22:15:48.650066007 +0200
@@ -641,6 +641,15 @@
 
        for (i = 0; i < size - 1; )
        {
+               /* check for insane values passed from application in "list": */
+               if (   list[i] <= 0 || list[i+1] <=0
+                   || list[i] > 1024 || list[i+1] > 1024)
+               {
+                       /* we cannot allow icons of negative or huge size,
+                          if only because incrementing "i" later would overflow */
+                       return;
+               }
+
                if (i + 1 + list[i]*list[i+1] < size)
                {
                        if (*best_w == 0 && *best_h == 0)
```

There may of course be other kinds of invalid values passed from the application that my above patch does not catch.
Please include either my above or a better sanity check into fvwm.

**Comment by ThomasAdam** [comment]
This check doesn't even come close to a correct solution. I'll look into it, but I can tell you now that you patch won't be the solution.  Thanks for the bug report though.

**Comment by lvml** [comment]
Any more correct solution is of course welcome - but maybe a simple fix like the one I suggested above could bridge the gap until a better fix becomes available?

**Comment by lvml** [comment]
Does your closing of this issue indicate you have no intent to fix this bug?

**Comment by ThomasAdam** [comment]
Hi,

This is correct. Keep it as a local patch for yourself.

Kindly,
Thomas
