### ISSUE TITLE
libfvwm could be built shared

### ISSUE THREAD

**Issue by dhduvall** [fvwmorg/fvwm#47]
For a local build of fvwm, I've modified `configure.ac` and a bunch of `Makefile.am` files to build libfvwm as a shared library, rather than a static archive.  It's not a huge win, but at half a meg scattered over about twenty executables, it adds up a bit.

The patch I have just forces it on; I'm not conversant enough with autoconf to know how to make it optional, but I wanted to suggest the enhancement; I'm attaching the patch ([shared-libfvwm.txt](https://github.com/fvwmorg/fvwm/files/1015043/shared-libfvwm.txt)) as it is if there's interest.  If there's only interest if it's completed, I can slowly work on that.

**Comment by dumblob** [comment]
I can't speak for FVWM core devs, but to me the patch looks good. It should also speed up compilation.

**Comment by SolarAquarion** [comment]
Create a Pull Request?

**Comment by dhduvall** [comment]
Done: PR #48

**Comment by shevegen** [comment]
*pokes sleepy devs*
