### ISSUE TITLE
FvwmCommandS does not handle pipe full correctly.

### ISSUE THREAD

**Issue by haroldsheep** [fvwmorg/fvwm#53]
There are two issues, but in the same area of code so I have submitted a single
report. All of the code is in FvwmCommandS.c:server().

The first issue is that the timeout structure (tv) is initialised once before
the select loop is entered. The select call can update this structure with the
amount of time left to wait. As a result the timeout can eventually become zero.
This will only happen as a result of the pipe becoming full for long enough.

The second issue is that if the a partial message is written when the pipe
becomes full, the code decides it is no longer queueing until a new message is
added to the queue. This is really only an issue of technical correctness
because:

a. It is only until a new message is added.
b. A partial write is very unlikely (at least on Linux) because writes of
   fewer the PIPE_BUF bytes are atomic (IIRC 4096 bytes) on Linux.

The following patch to fix both issues.

diff --git a/modules/FvwmCommandS/FvwmCommandS.c b/modules/FvwmCommandS/FvwmCommandS.c
index 977d52e..bd51183 100644
--- a/modules/FvwmCommandS/FvwmCommandS.c
+++ b/modules/FvwmCommandS/FvwmCommandS.c
@@ -158,10 +158,6 @@ void server (char *name)
   char buf[MAX_MODULE_INPUT_TEXT_LEN + 1];  /* command receiving buffer */
   char cmd[MAX_MODULE_INPUT_TEXT_LEN + 1];
   int  ix,cix;
-  struct timeval tv;
-
-  tv.tv_sec = 10;
-  tv.tv_usec = 0;
 
   if (name == NULL)
   {
@@ -190,6 +186,8 @@ void server (char *name)
   while (!isTerminated)
   {
     int ret;
+    struct timeval tv;
+    struct timeval *tv_pointer = NULL;
 
     FD_ZERO(&fdrset);
     FD_ZERO(&fdwset);
@@ -198,7 +196,13 @@ void server (char *name)
     if (queueing)
       FD_SET(FfdM, &fdwset);
 
-    ret = fvwmSelect(FD_SETSIZE, &fdrset, &fdwset, 0, queueing ? &tv : NULL);
+    if (queueing)
+    {
+        tv.tv_sec = 10;
+        tv.tv_usec = 0;
+        tv_pointer = &tv;
+    }
+    ret = fvwmSelect(FD_SETSIZE, &fdrset, &fdwset, 0, tv_pointer);
 
     if (ret < 0)
       continue;
@@ -234,7 +238,7 @@ void server (char *name)
 
       /* there is either one message left (partially complete) or none */
       Qlast = Qstart;
-      queueing = False;
+      queueing = Qlast != NULL;    /* Still queue if after partial send. */
       continue;
     }

**Comment by paul-ollis** [comment]
I have noticed that the patch text is unusable in-line. I tried to add as an attachment but patches did not seem to be a supported type. Advice gratefully received.

**Comment by ThomasAdam** [comment]
Thanks, but I have no interest in fixing this.  It's all but dead code that won't be round much longer.
