### ISSUE TITLE
Remove built in __DATE__ and __TIME__

### ISSUE THREAD

**Issue by ng-0** [fvwmorg/fvwm#67]
Hi,

I had an itch to scratch with reproducible builds. The patch is a slightly adjusted variant of robert@openbsd done in the Xenocara tree version of FVWM. What this fixes can be read about here: https://reproducible-builds.org/docs/timestamps/

I hope this still applies on latest master, it is a patch I apply on the latest release:

https://git.infotropique.org/infotropique/sources/x11/fvwm/patch/?id=90e0ab0a5d5eae066f670723cd4c20f113e664be

if you want it and it doesn't apply anymore, I can rework it apply to master.

**Comment by ThomasAdam** [comment]
Thanks.

I don't think I'll be applying this to fvwm2, but when fvwm3 gets off the ground, this won't be a problem.
