### ISSUE TITLE
Ignore focus request submitted by window

### ISSUE THREAD

**Issue by seb321** [fvwmorg/fvwm#68]
Hi,

I want to configure fvwm not to allow any window to grab focus itself (e.g. when it is created), but fvwm man page says:
>New normal or transient windows with the FPGrabFocus or FPGrabFocusTransient style automatically receive the focus when they are created.  FPGrabFocus is the default for windows with the ClickToFocus style.  **Note that even if these styles are disabled, the application may take the focus itself.  Fvwm can not prevent this.**

I wonder why it is so, it does not sound like impossible thing. I think that fvwm should support such option, it seems reasonable to me. I think that most people do not want windows to steal focus without asking.

**Comment by ThomasAdam** [comment]
See:  http://fvwmforums.org/wiki/Tips/FocusStealing/

**Comment by seb321** [comment]
It was fast, thanks.

**Comment by seb321** [comment]
By the way, don't you think that fvwm man page is misleading? I think that quoted paragraph should be rewritten.
