### ISSUE TITLE
iconman's Colorset option is useless when swallow it into fvwmbutton

### ISSUE THREAD

**Issue by chenjie199234** [fvwmorg/fvwm#73]
there is a problem when swallow iconman into fvwnbutton
i use roottransparent to let it be transparent
but the background of iconman sometimes will not be transparent
it will be filled with background image
when i restart,it will be transparent sometimes
here is the screen shot,look at the buttom of the image
![2019-02-05-000939_1920x1080_scrot](https://user-images.githubusercontent.com/29348971/52221253-bd46e680-28db-11e9-9946-023ae620eda4.png)

**Comment by ThomasAdam** [comment]
Have you tried the ParentRelative style option?

**Comment by chenjie199234** [comment]
@ThomasAdam yes,i use ParentalRelativity option in style,but it changed nothing!

##########          ALL          ##########
Style * !Title,BorderWidth 1,HandleWidth 1,FvwmBorder,FirmBorder,SloppyFocus,MouseFocusClickRaises,!Icon
Style * TitleCascadePlacement,GrabFocusOff,!UsePPosition
Style * WindowShadeScrolls,WindowShadeSteps 10
Style * DecorateTransient,StackTransientParent,!FPGrabFocusTransient,FPReleaseFocusTransient
Style * ResizeOpaque,SnapAttraction 15 SameType ScreenAll,SnapGrid

EwmhBaseStruts 0 0 0 0
EdgeScroll 0 0
ClickTime 400
DeskTopSize 2x2
HideGeometryWindow
OpaqueMoveSize unlimited
IgnoreModifiers L25
Colorset 0 RootTransparent buffer,Tint black 0
Colorset 1 RootTransparent buffer,Tint black 20
Colorset 2 RootTransparent buffer,Tint black 40
Colorset 3 RootTransparent buffer,Tint black 60
Colorset 4 fg black,bg white,sh white,hi white

##########          StartFunction          ##########
DestroyFunc StartFunction
AddToFunc StartFunction
+ I Module FvwmButtons MyButtons

##########          InitFunction         ###########
DestroyFunc InitFunction
AddToFunc InitFunction
+ I Exec fvwm-root -r /usr/share/fvwm/icons/background.png
+ I Exec fcitx

#########           SessionInitFunction       ###########
DestroyFunc SessionInitFunction
AddToFunc SessionInitFunction
+ I Exec fvwm-root -r /usr/share/fvwm/icons/background.png
+ I Exec fcitx

##########          Menu          #############
Colorset 5 fg black, bg white,hi,sh,Plain,NoShape
Colorset 6 fg white, bg grey20,hi,sh,Plain,NoShape
Colorset 7 fg white, bg #0066CC,hi,sh,Plain,NoShape
MenuStyle * MenuColorset 5,ActiveColorset 6,TitleColorset 7,HilightBack,HilightTitleBack,Hilight3DOff
MenuStyle * SeparatorsLong,TitleUnderLines0,Borderwidth 1,TrianglesSolid,TrianglesUseFore
MenuStyle * Animation,PopupImmediately,PopdownImmediately,PopupOffset 0 100,!TitleWarp
MenuStyle * ItemFormat "%|%3.1i%5.3l%5.3>%|"
MenuStyle * Font "xft:Noto Sans Mono CJK SC:style=Bold:Size=10"

DestroyMenu MenuRoot
AddToMenu MenuRoot $[USER] Title
+ "Tools%/usr/share/fvwm/icons/tools.png%" Popup MenuTools
+ "Apps%/usr/share/fvwm/icons/apps.png%" Popup MenuApps
+ "Terminal%/usr/share/fvwm/icons/terminal.png%" Exec lxterminal
+ "" Nop
+ "Identify%/usr/share/fvwm/icons/ident.png%" Module FvwmIdent
+ "Refresh%/usr/share/fvwm/icons/refresh.png%" Refresh
+ "Restart%/usr/share/fvwm/icons/restart.png%" Restart
+ "" Nop
+ "Quit%/usr/share/fvwm/icons/quit-menu.png%" Popup MenuQuit

DestroyMenu MenuTools
AddToMenu MenuTools "Tools" Title
+ "FvwmConfig" Exec lxterminal -e nvim /usr/share/fvwm/config
+ "VimConfig" Exec lxterminal -e nvim /usr/share/nvim/sysinit.vim

DestroyMenu MenuApps
AddToMenu MenuApps "Apps" Title
Test (x putty) + "Putty" Exec putty
Test (x codeblocks) + "CodeBlocks" Exec codeblocks
Test (x blender) + "Blender" Exec blender
Test (x darktable) + "Darktable" Exec darktable
Test (x rawtherapee) + "Rawtherapee" Exec rawtherapee
Test (x gimp) + "Gimp" Exec gimp

DestroyMenu MenuQuit
AddToMenu MenuQuit "Quit" Title
+ "Shutdown" Module FvwmForm Form-ShutdownConfirm
+ "Reboot" Module FvwmForm Form-RebootConfirm
+ "QuitFvwm" Module FvwmForm Form-QuitConfirm

##########          FvwmForm              ##########
Style FvwmForm !Title,HandleWidth 5,WindowListSkip,CirculateSkip,!Maximizable
*FvwmFormDefault: Font "xft:Noto Sans Mono CJK SC:style=Bold:size=10"
*FvwmFormDefault: ButtonFont "xft:Noto Sans Mono CJK SC:style=Bold:size=10"
*FvwmFormDefault: TimeoutFont "xft:Noto Sans Mono CJK SC:style=Bold:size=10"
*FvwmFormDefault: Fore black
*FvwmFormDefault: Back white
*FvwmFormDefault: ButtonPointerFore blue
*FvwmFormDefault: ButtonPointerBack grey
*FvwmFormDefault: ButtonInPointerFore grey
*FvwmFormDefault: ButtonInPointerBack blue
DestroyModuleConfig  Form-ShutdownConfirm: *
*Form-ShutdownConfirm: GrabServer
*Form-ShutdownConfirm: WarpPointer
*Form-ShutdownConfirm: Line        center
*Form-ShutdownConfirm: Text        "Realy want to shutdown?"
*Form-ShutdownConfirm: Line        center
*Form-ShutdownConfirm: Timeout     10 "Exec poweroff" "Shutdown in %% seconds."
*Form-ShutdownConfirm: Line        expand
*Form-ShutdownConfirm: Button      quit "Yes"
*Form-ShutdownConfirm: Command     Exec poweroff
*Form-ShutdownConfirm: Button      quit "No"
*Form-ShutdownConfirm: Command     Nop
DestroyModuleConfig  Form-RebootConfirm: *
*Form-RebootConfirm: GrabServer
*Form-RebootConfirm: WarpPointer
*Form-RebootConfirm: Line        center
*Form-RebootConfirm: Text        "Realy want to reboot?"
*Form-RebootConfirm: Line        center
*Form-RebootConfirm: Timeout     10 "Exec reboot" "Reboot in %% seconds."
*Form-RebootConfirm: Line        expand
*Form-RebootConfirm: Button      quit "Yes"
*Form-RebootConfirm: Command     Exec reboot
*Form-RebootConfirm: Button      quit "No"
*Form-RebootConfirm: Command     Nop
DestroyModuleConfig  Form-QuitConfirm: *
*Form-QuitConfirm: GrabServer
*Form-QuitConfirm: WarpPointer
*Form-QuitConfirm: Line        center
*Form-QuitConfirm: Text        "Realy want to quit fvwm?"
*Form-QuitConfirm: Line        center
*Form-QuitConfirm: Timeout     10 "Exec reboot" "Quit fvwm in %% seconds."
*Form-QuitConfirm: Line        expand
*Form-QuitConfirm: Button      quit "Yes"
*Form-QuitConfirm: Command     Quit
*Form-QuitConfirm: Button      quit "No"
*Form-QuitConfirm: Command     Nop
DestroyModuleConfig  Form-ScreenShot: *
*Form-ScreenShot: GrabServer
*Form-ScreenShot: WarpPointer
*Form-ScreenShot: Line        center
*Form-ScreenShot: Text        "Press left mouse and move to select an ared!"
*Form-ScreenShot: Line        center
*Form-ScreenShot: Text        "Or left click to select a window!"
*Form-ScreenShot: Line        center
*Form-ScreenShot: Text        "Screenshot file will put in ~ direcroty!"
*Form-ScreenShot: Line        expand
*Form-ScreenShot: Button      quit "Start"
*Form-ScreenShot: Command     Exec scrot -s -e 'mv $f ~'
*Form-ScreenShot: Button      quit "Cancel"
*Form-ScreenShot: Command     Nop

Key 1 A CM Exec lxterminal
Key 2 A CM Exec chromium --incognito
Key 3 A CM Exec pcmanfm
Key 4 A CM Exec mocp -S;mocp -o r;mocp -o s;mocp -a ~/Music/;mocp -p
Key 9 A CM Maximize
Key 0 A CM Iconify
Key Right A CM Exec mocp -f
Key Left A CM Exec mocp -r
Key Print A Nop Exec scrot
Key u A CM GotoPage 0 0
Key i A CM GotoPage 1 0
Key o A CM GotoPage 0 1
Key p A CM GotoPage 1 1
DestroyFunc MoveClickX
AddToFunc MoveClickX
+ M $0
+ C $1
+ D $2
Mouse 1 R N Nop
Mouse 3 R N Menu MenuRoot
Mouse 1 2 A MoveClickX Nop Close Destroy
Mouse 1 4 A Maximize
Mouse 1 6 A Iconify
Mouse 1 T	A MoveClickX Move Raise Maximize
Mouse 4 TFS	A MoveClickX Nop Raise "WindowShade True"
Mouse 5 TFS	A MoveClickX Nop Raise "WindowShade False"
Mouse 1 FS	A MoveClickX Resize Raise Maximize

##########          ToggleFunction           #########
#DestroyFunc ToggleMpd
#AddToFunc ToggleMpd
#+ I ToggleFunction config-mpd.script "Module FvwmScript config-mpd.script"

#DestroyFunc ToggleFunction
#AddToFunc ToggleFunction
#+ I None ($$0,CirculateHit) $$1
#+ I TestRc (Match) Break
#+ I Next (currentpage,Visible,!iconic,$$0,CirculateHit) Close
#+ I TestRc (Match) Break
#+ I Next ($$0,CirculateHit) Function MakeVisible

#DestroyFunc MakeVisible
#AddToFunc MakeVisible
#+ I MoveToDesk
#+ I MoveToPage
#+ I MoveToScreen
#+ I Iconify off
#+ I WindowShade off

##########          CursorStyle          ##########
CursorStyle DEFAULT left_ptr
CursorStyle TITLE left_ptr
CursorStyle MENU left_ptr
CursorStyle POSITION left_ptr
#CursorStyle SYS pointer

##########          FvwmButtons          ##########
Style FvwmButtons !Title,WindowListSkip,CirculateSkip,BorderWidth 0,HandleWidth 0,Sticky,StaysOnButton,NeverFocus,ParentalRelativity
         #####      MyButtons     ######
*MyButtons: Columns 1920 
*MyButtons: Rows 60
*MyButtons: Frame 0
*MyButtons: BoxSize fixed
*MyButtons: Colorset 0
*MyButtons: ActiveColorset 1
*MyButtons: PressColorset 2
*MyButtons: Padding 0 0
*MyButtons: Geometry +0-0
*MyButtons: (60x60,Icon "/usr/share/fvwm/icons/filemanager-min.png",ActiveIcon "/usr/share/fvwm/icons/filemanager-max.png",Action (Mouse 1) "Exec pcmanfm",Action (Mouse 3) "Exec pkill pcmanfm")
*MyButtons: (60x60,Icon "/usr/share/fvwm/icons/music-min.png",ActiveIcon "/usr/share/fvwm/icons/music-max.png",Action (Mouse 1) "Exec mocp -S;mocp -o r;mocp -o s;mocp -a ~/Music/;mocp -p",Action (Mouse 3) "Exec mocp -x")
*MyButtons: (60x60,Icon "/usr/share/fvwm/icons/term-min.png",ActiveIcon "/usr/share/fvwm/icons/term-max.png",Action (Mouse 1) "Exec lxterminal",Action (Mouse 3) "Exec pkill lxterminal") 
*MyButtons: (60x60,Icon "/usr/share/fvwm/icons/browser-min.png",ActiveIcon "/usr/share/fvwm/icons/browser-max.png",Action (Mouse 1) "Exec chromium --incognito",Action (Mouse 3) "Exec pkill chromium")
*MyButtons: (860x60,Swallow FvwmIconMan 'Module FvwmIconMan',Colorset 0,ActiveColorset 0,PressColorset 0)
*MyButtons:(640x60,Swallow conky 'Exec conky -q',Colorset 0,ActiveColorset 0,PressColorset 0)
*MyButtons: (30x30+1740+0,Icon "/usr/share/fvwm/icons/pause-min.png",ActiveIcon "/usr/share/fvwm/icons/pause-max.png",Action (Mouse 1) "Exec mocp -P")
*MyButtons: (30x30+1770+0,Icon "/usr/share/fvwm/icons/play-min.png",ActiveIcon "/usr/share/fvwm/icons/play-max.png",Action (Mouse 1) "Exec mocp -U")
*MyButtons: (30x30+1740+30,Icon "/usr/share/fvwm/icons/left-min.png",ActiveIcon "/usr/share/fvwm/icons/left-max.png",Action (Mouse 1) "Exec mocp -r")
*MyButtons: (30x30+1770+30,Icon "/usr/share/fvwm/icons/right-min.png",ActiveIcon "/usr/share/fvwm/icons/right-max.png",Action (Mouse 1) "Exec mocp -f")
*MyButtons: (60x60,Swallow FvwmPager 'Module FvwmPager *',Colorset 0,ActiveColorset 0,PressColorset 0)
*MyButtons: (30x30+1860+0,Icon "/usr/share/fvwm/icons/calculator-min.png",ActiveIcon "/usr/share/fvwm/icons/calculator-max.png",Action (Mouse 1) "Exec galculator",Action (Mouse 3) "Exec pkill galculator")
#*MyButtons: (30x30+1890+0,Icon "/usr/share/fvwm/icons/printscreen-min.png",ActiveIcon "/usr/share/fvwm/icons/printscreen-max.png",Action (Mouse 1) "Menu MenuQuit rectangle 30x30-0-60 c -100m-0p")
*MyButtons: (30x30+1890+0,Icon "/usr/share/fvwm/icons/printscreen-min.png",ActiveIcon "/usr/share/fvwm/icons/printscreen-max.png",Action (Mouse 1) "Module FvwmForm Form-ScreenShot")
*MyButtons: (30x30+1860+30,Icon "/usr/share/fvwm/icons/sound-min.png",ActiveIcon "/usr/share/fvwm/icons/sound-max.png",Action (Mouse 1) "Exec lxterminal -e pulsemixer",Action (Mouse 3) "Exec pkill pulsemixer")
#*MyButtons: (30x30+1860+30,Icon "/usr/share/fvwm/icons/sound-min.png",ActiveIcon "/usr/share/fvwm/icons/sound-max.png",Action (Mouse 1) "Exec lxterminal -e alsamixer",Action (Mouse 3) "Exec pkill alsamixer")
*MyButtons: (30x30+1890+30,Icon "/usr/share/fvwm/icons/wifi-min.png",ActiveIcon "/usr/share/fvwm/icons/wifi-max.png",Action (Mouse 1) "Exec lxterminal -e sudo wifi-menu")

##########          FvwmPager          ##########
Style FvwmPager NoTitle,WindowListSkip,CirculateSkip,BorderWidth 0,HandleWidth 0,Sticky,StaysOnButton,ParentalRelativity
*FvwmPager: UseSkipList
*FvwmPager: Geometry 60x60-120-0
*FvwmPager: NoStartIconic
*FvwmPager: NoShapeLabels
*FvwmPager: Font None
*FvwmPager: Colorset * 0
*FvwmPager: HilightColorset * 1
*FvwmPager: WindowBorderWidth 0

##########          FvwmIconMan         #############
Style FvwmIconMan NoTitle,WindowListSkip,CirculateSkip,BorderWidth 0,HandleWidth 0,Sticky,StaysOnButton,ParentalRelativity

DestroyFunc IconManClick
AddToFunc IconManClick
+ I ThisWindow (Raised,!Shaded,!Iconic,CurrentPage) Iconify
+ I TestRc (Match) Break
+ I ThisWindow (!Raised) Raise
+ I ThisWindow (Shaded) WindowShade
+ I ThisWindow (Iconic) Iconify
+ I ThisWindow (AcceptsFocus) FlipFocus

*FvwmIconMan: Colorset 0
*FvwmIconMan: PlainColorset 1
*FvwmIconMan: FocusColorset 0
*FvwmIconMan: FocusAndSelectColorset 3
*FvwmIconMan: SelectColorset 3
*FvwmIconMan: IconColorset 2
*FvwmIconMan: IconAndSelectColorset 3
*FvwmIconMan: DrawIcons false
*FvwmIconMan: Format "%t"
*FvwmIconMan: Font "xft:Noto Sans Mono CJK SC:style=Bold:size=10"
*FvwmIconMan: ReliefThickness 0
*FvwmIconMan: UseWinList true
*FvwmIconMan: ButtonGeometry 215x20
*FvwmIconMan: ManagerGeometry 4x3
*FvwmIconMan: MaxButtonWidth 215
*FvwmIconMan: Resolution page
*FvwmIconMan: Sort id
*FvwmIconMan: Action Mouse 1 N sendcommand IconManClick
*FvwmIconMan: Action Mouse 2 A sendcommand Nop
*FvwmIconMan: Action Mouse 3 N sendcommand "MoveClickX Nop Close Destroy"

##########          FvwmIdent           ##########
Style FvwmIdent WindowListSkip,CirculateSkip,!Borders,!Handles
*FvwmIdent: Colorset 4
*FvwmIdent: Font "xft:Noto Sans Mono CJK SC:style=Bold:size=10"

##########          ExitFunction          ##########
DestroyFunc ExitFunction
AddToFunc ExitFunction
+ I pkill conky
+ I pkill fcitx
+ I Exec sync
