### ISSUE TITLE
Transient FvwmPager with SloppyFocus on focus_change grab

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm#77]
Hello again.

While I have been working on my FVWM-based CDE clone NsCDE, I have
touched probably every corner of main program and most of the modules.
Altrough FVWM is robust and mainly without obvious bugs in my general
experiance, during past months of intensive work on my hobby, I have
found a few of them, so let's begin with FvwmPager.

You decide if it is worth fixing in the mainline.

Version:
2.6.7, 2.6.8 ...

Description:
Transient FvwmPager with SloppyFocus option defined fails if FwmEvent
executes some function, even with only "Nop" action on "focus_change"
window manager event.

Symptoms:
When pager configured as in description is called either from Script,
keybinding or FvwmCommand (that is, this context doesn't matter), and
some window inside pager is clicked during the first 3-4 seconds, this
action fails, desk/page is not changed and window is not selected.
If I wait for a 3-5 seconds before clicking on Pager, the error below
will still be printed, but action will suceed.

Output (~/.xsession-errors):
[fvwm][ComplexFunction]: <<ERROR>> Grab failed in function
f_FocusChange 0x200000b, unable to execute immediate action

Workaround:
Not using SloppyFocus FvwmPager option is a best compromise, since it
must be transient and handling focus_change is important, and I cannot
exclude FvwmPager in the function since problem occurs even if
f_FocusChange is doing simple "Nop".

**Comment by ThomasAdam** [comment]
This isn't a bug.
