### ISSUE TITLE
Display resolution/configuration changes (rotation) require restarting FVWM

### ISSUE THREAD

**Issue by wyatt8740** [fvwmorg/fvwm#81]
There appears to be no way to make FVWM update what it sees as the display resolution after using `xrandr` to, for instance, rotate the display.
The result is that, upon rotating my 1920x1200 screen into portrait mode (1200x1920), maximizing a window will make it fill to 1200px high, leaving 720 pixels vertically unused, and stretch 720 pixels off the edge of the display. The only thing I have found that will fix this is restarting FVWM, which gets annoying as it takes multiple seconds.

I'd therefore suggest a command that can be used to make FVWM recalculate display size/monitor layout without a `Restart`. That way, I could have `FvwmCommand RecalculateGeometry` or similar automatically run after a resolution change, and solve the issue. Optionally, currently mapped maximized windows could also be adjusted, but that'd just be a nice bonus.

Alternatively, some window managers appear to be able to monitor for changes to resolution/display configuration and adjust automatically (MATE's marco, GNOME's metacity).

This would be especially useful for my Thinkpad X201 tablet, which is a convertible that I like to use FVWM on.

**Comment by ThomasAdam** [comment]
That's right.  I have a `ta/xrandr` branch in the fvwm tree you can check, which tries to address this problem.

But you're forgetting that fvwm doesn't support RANDR as a first-class citizen; only Xinerama, so you're expectations are already off.
