### ISSUE TITLE
fvwm man page is not created if you don't explicitly specify --enable-mandoc

### ISSUE THREAD

**Issue by ecasaert** [fvwmorg/fvwm#86]
Since fvwm 2.6.9, the fvwm man page is not built if you don't specify --enable-mandoc as a configure option.
This problem seems related to commit 0fdf281 and commit 818c0a9.

I think that the solution is to modify line 385 of the configure.ac file at the root of the project with :
`[ with_mandoc="yes" ]`

**Comment by ThomasAdam** [comment]
Nope. This is how it is now.
