### ISSUE TITLE
Is there a possibility to use deallocated data?

### ISSUE THREAD

**Issue by klebertarcisio** [fvwmorg/fvwm#89]
I believe that we need an improvement in this code. See that on line 579 we call the FCreateFImage () function, but this function can return a deallocated data.

https://github.com/fvwmorg/fvwm/blob/f29b7d1354d6ca22193b2326abfc27be663364ef/libs/PictureGraphics.c#L579-L580

Soon after, on line 600 we use data that may be deallocated. I believe there must be a check. What do you think?

https://github.com/fvwmorg/fvwm/blob/f29b7d1354d6ca22193b2326abfc27be663364ef/libs/PictureGraphics.c#L599-L601

Regards

**Comment by ThomasAdam** [comment]
Hi,

No, I don't think so.  `FCreateFImage` will fail if malloc isn't possible.

If you still think this going to cause a problem, by all means send a patch, but this should be against fvwm/fvwm3, as I'm no longer maintaining this version.

**Comment by klebertarcisio** [comment]
Hi, @ThomasAdam . Thanks for the answer.
